repos:
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.17.0"
    hooks:
      - id: terraform-docs-go
        args:
          - "--output-file"
          - "README.md"
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.88.4"
    hooks:
      - id: terraform_fmt
